/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package colomboios;

    import java.sql.*;
    import javax.swing.JTextField;
    import java.sql.DriverManager;
    import java.sql.Connection;
    import java.sql.PreparedStatement;
    import java.sql.ResultSet;
    import javax.swing.JOptionPane;



public class Assis_add extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "";
    private static final String dataConn = "jdbc:mysql://localhost:3306/employee";
    
    Connection sqlConn,sqlconn1 = null;
    PreparedStatement pst,pst1 = null;
    ResultSet rs = null;
    int n1,n2; 
    
    
    
    public Assis_add() {
        initComponents();
         dep();
    design();
    }
    
    
      
    public void dep()
       {
        try
       {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn, username,password);
                Statement st = sqlConn.createStatement();
                rs = st.executeQuery("SELECT Department FROM add_department");
                while(rs.next())
                {
                    dep.addItem(rs.getString("Department"));
                }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
      }
    
    
    
     public void design()
       {
        try
       {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn, username,password);
                Statement st = sqlConn.createStatement();
                rs = st.executeQuery("SELECT Designation FROM add_designation");
                while(rs.next())
                {
                    design.addItem(rs.getString("Designation"));
                }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
      }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        gen = new javax.swing.JComboBox<>();
        dob = new com.toedter.calendar.JDateChooser();
        add = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        edu = new javax.swing.JComboBox<>();
        empid = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        epf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dep = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        design = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel11.setText("Education");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 138, 34));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("EXIT");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 620, 138, 41));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel12.setText("Gender");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 138, 34));

        name.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 273, 33));

        nic.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 272, 34));

        gen.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 273, 34));

        dob.setDateFormatString("y /MM / d");
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 272, 34));

        add.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 272, 34));

        contact.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 272, 34));

        email.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 272, 34));

        edu.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        edu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GCE O/L", "GCE A/L", "DIPLOMA", "HIGHER DIPLOMA", "DEGREE", "OTHER" }));
        jPanel1.add(edu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 272, 34));

        empid.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        empid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empidActionPerformed(evt);
            }
        });
        jPanel1.add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 272, 34));

        salary.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jPanel1.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 272, 34));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 138, 33));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jButton1.setText("ADD EMPLOYEE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, 419, 48));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Birthday");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 138, 34));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 137, 41));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setText("Contact Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 34));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel13.setText("EPF No.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 105, 34));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 138, 34));

        epf.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jPanel1.add(epf, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 272, 34));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel5.setText("E-mail");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 138, 34));

        dep.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR", "Marketing" }));
        dep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depItemStateChanged(evt);
            }
        });
        dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depActionPerformed(evt);
            }
        });
        jPanel1.add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 271, 34));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setText("Department");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 111, 34));

        design.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        design.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Assistant", "Administrator" }));
        design.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                designItemStateChanged(evt);
            }
        });
        jPanel1.add(design, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 271, 36));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setText("Designation");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 111, 34));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setText("Employee ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel9.setText("NIC No.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 138, 34));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel10.setText("Salary");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 108, 30));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("CLEAR ALL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 147, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void empidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username,password);

            if(empid.getText().equals("")||
                name.getText().equals("")||
                gen.getSelectedItem().equals("")||
                nic.getText().equals("")||
                ((JTextField)dob.getDateEditor().getUiComponent()).getText().equals("")||
                add.getText().equals("")||
                contact.getText().equals("")||
                email.getText().equals("")||
                edu.getSelectedItem().toString().equals("")||
                dep.getSelectedItem().toString().equals("")||
                design.getSelectedItem().toString().equals("")||
                salary.getText().equals("")||
                epf.getText().equals("")    )

            {
                JOptionPane.showMessageDialog(this, "Entering All Informations are Mandatory......");
            }

            else{
                pst = sqlConn.prepareStatement("insert into employee_details (Employee_ID, Name, Gender, NIC, DOB, Address,  Contact_no, Email, Education, Department, Designation, Salary , EPF_no) value (?,?,?,?,?,?,?,?,?,?,?,?,?)");
                pst.setString(1, empid.getText());
                pst.setString(2, name.getText());

                String selectValue3 = gen.getSelectedItem().toString();
                pst.setString(3, selectValue3);

                pst.setString(4, nic.getText());

                String selectdate = ((JTextField)dob.getDateEditor().getUiComponent()).getText();
                pst.setString(5, selectdate);

                pst.setString(6, add.getText());

                pst.setString(7, contact.getText());

                pst.setString(8, email.getText());

                String selectValue9 = edu.getSelectedItem().toString();
                pst.setString(9, selectValue9);

                String selectValue10 = dep.getSelectedItem().toString();
                pst.setString(10, selectValue10);

                String selectValue11 = design.getSelectedItem().toString();
                pst.setString(11, selectValue11);

                pst.setString(12, salary.getText());

                pst.setString(13, epf.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Employee Added Successfully");

                HR_manager hrm = new HR_manager();
                hrm.setVisible(true);
                this.hide();
            }
        }

        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HR_assistant hra = new HR_assistant();
        hra.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void depItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depItemStateChanged

    }//GEN-LAST:event_depItemStateChanged

    private void depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depActionPerformed

    }//GEN-LAST:event_depActionPerformed

    private void designItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_designItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_designItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        empid.setText("");
        name.setText("");
        gen.setSelectedItem("");
        nic.setText("");
        ((JTextField)dob.getDateEditor().getUiComponent()).setText("");
        add.setText("");
        contact.setText("");
        email.setText("");
        edu.setSelectedItem("");
        dep.setSelectedItem("");
        design.setSelectedItem("");
        salary.setText("");
        epf.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assis_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assis_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assis_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assis_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assis_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField add;
    public javax.swing.JTextField contact;
    public javax.swing.JComboBox<String> dep;
    private javax.swing.JComboBox<String> design;
    public com.toedter.calendar.JDateChooser dob;
    public javax.swing.JComboBox<String> edu;
    public javax.swing.JTextField email;
    public javax.swing.JTextField empid;
    private javax.swing.JTextField epf;
    public javax.swing.JComboBox<String> gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField name;
    public javax.swing.JTextField nic;
    private javax.swing.JTextField salary;
    // End of variables declaration//GEN-END:variables
}
