/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package colomboios;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class HR_manager_acc extends javax.swing.JFrame {
    
    
    private static final String username = "root";
    private static final String password = "";
    private static final String dataConn = "jdbc:mysql://localhost:3306/employee";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public HR_manager_acc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        hr_user = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hr_email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hr_seq = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        hr_pass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hr_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        hr_id = new javax.swing.JTextField();
        hr_ansr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("CREATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 515, 290, 40));

        hr_user.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(hr_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 270, -1));

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel6.setText("EMAIL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 136, 30));

        hr_email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(hr_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 270, -1));

        jLabel7.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel7.setText("SECURITY QUESTION");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 185, 30));

        jLabel8.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel8.setText("ANSWER");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 185, -1));

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel3.setText("MANAGER ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 136, 30));

        hr_seq.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hr_seq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What's your favourite Country?", "When you joined the Company?", "When is your Birthday?", " " }));
        jPanel1.add(hr_seq, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 270, -1));

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel4.setText("USERNAME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 185, -1));

        hr_pass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(hr_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 268, -1));

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel5.setText("PASSWORD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 191, -1));

        jLabel9.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel9.setText("NAME");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 158, 27));

        hr_name.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(hr_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 270, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 569, 120, 40));

        hr_id.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(hr_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 270, -1));

        hr_ansr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(hr_ansr, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 270, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 36)); // NOI18N
        jLabel1.setText("HR MANAGER NEW ACCOUNT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 29));

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 570, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
      {
         Class.forName("com.mysql.jdbc.Driver");
         sqlConn = DriverManager.getConnection(dataConn, username,password);
        if(
            hr_name.getText().equals("")||
            hr_email.getText().equals("")||
            hr_seq.getSelectedItem().equals("")||     
            hr_id.getText().equals("")||      
            hr_ansr.getText().equals("")||
            hr_user.getText().equals("")||      
            hr_pass.getText().equals("") )      
         {
            JOptionPane.showMessageDialog(this, "Entering All Informations are Mandatory......"); 
         } 
         else
         {
         pst = sqlConn.prepareStatement("insert into hr_manager (Name, Email, Manager_id, Security_ques, Answer, Username, Password) value (?,?,?,?,?,?,?)");
         pst.setString(1, hr_name.getText());
         pst.setString(2, hr_email.getText()); 
         pst.setString(3, hr_id.getText());
         
         String selectValue4 = hr_seq.getSelectedItem().toString();
         pst.setString(4, selectValue4);
         pst.setString(5, hr_ansr.getText());
         pst.setString(6, hr_user.getText());
         pst.setString(7, hr_pass.getText());
         
         pst.executeUpdate();
         JOptionPane.showMessageDialog(this, "HR Manger Account Create Successfully.......");
         
          Admin admin = new Admin();
          admin.setVisible(true);
          this.hide();
        }
      }
        catch(Exception ex)
      {
         JOptionPane.showMessageDialog(this, "Entering All the Informations Mandatory.......");
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Admin admin = new Admin();
        admin.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HR_manager_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HR_manager_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HR_manager_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HR_manager_acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HR_manager_acc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hr_ansr;
    private javax.swing.JTextField hr_email;
    private javax.swing.JTextField hr_id;
    private javax.swing.JTextField hr_name;
    private javax.swing.JTextField hr_pass;
    private javax.swing.JComboBox<String> hr_seq;
    private javax.swing.JTextField hr_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
