/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package colomboios;

import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
 import javax.swing.JTextField;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class Search_interface extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "";
    private static final String dataConn = "jdbc:mysql://localhost:3306/employee";
    
    Connection sqlConn = null;
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int n1,n2; 
    
    public Search_interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        employee_id11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton5.setText("jButton5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 134, 40));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 134, 40));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("Employee ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 164, 34));

        employee_id11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        employee_id11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_id11ActionPerformed(evt);
            }
        });
        jPanel2.add(employee_id11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 282, 34));

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 160, 48));

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 18)); // NOI18N
        jButton3.setText("REMOVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 160, 48));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try
     {
         Class.forName("com.mysql.jdbc.Driver");
         sqlConn = DriverManager.getConnection(dataConn, username,password);
         pst = sqlConn.prepareStatement("select Employee_ID, Name, Gender, NIC, DOB, Address, Contact_no, Email, Education, Department, Designation, Salary, EPF_no from employee_details  Where Employee_ID = ?");
         int Employee_ID = Integer.parseInt(employee_id11.getText());
         pst.setInt(1, Employee_ID);
         rs = pst.executeQuery();
         if(rs.next() == true)
        {
             String Employee_ID1 = String.valueOf(rs.getInt("Employee_ID"));
             String Name = rs.getString("Name");
             String Gender = rs.getString("Gender");
             String NIC = rs.getString("NIC");
             String DOB = rs.getString("DOB");
             String Address = rs.getString("Address");
             String Contact_no = String.valueOf(rs.getString("Contact_no"));
             String Email = rs.getString("Email");
             String Education = rs.getString("Education");
             String Department = rs.getString("Department");
             String Designation = rs.getString("Designation");
             String Salary = String.valueOf(rs.getInt("Salary"));
             String EPF_no = String.valueOf(rs.getString("EPF_no"));
             
             String tbData[] = { Employee_ID1, Name, Gender, NIC, DOB, Address, Contact_no, Email, Education, Department, Designation, Salary, EPF_no };
             
             Search srh = new Search();
              
             DefaultTableModel tblModel;
             tblModel = (DefaultTableModel) srh.es_table.getModel();
             tblModel.addRow(tbData);
             
             srh.setVisible(true);
             this.hide();
         } 
         else
         {
             JOptionPane.showMessageDialog(this, "Employee ID not found.......");
             employee_id11.setText("");
         }
     }   
          catch(Exception ex)
      {
         JOptionPane.showMessageDialog(this, "Employee ID not found.......");
      }      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
  try
     {
         Class.forName("com.mysql.jdbc.Driver");
         sqlConn = DriverManager.getConnection(dataConn, username,password);
         pst = sqlConn.prepareStatement("select Employee_ID, Name, Gender, NIC, DOB, Address, Contact_no, Email, Education, Department, Designation, Salary, EPF_no from employee_details  Where Employee_ID = ?");
         String Employee_ID = (employee_id11.getText());
         pst.setString(1, Employee_ID);
         rs = pst.executeQuery();
         if(rs.next() == true)
         
         {
             String Employee_ID1 =rs.getString("Employee_ID");
             String Name = rs.getString("Name");
             String Gender = rs.getString("Gender");
             String NIC = rs.getString("NIC");
             String DOB = rs.getString("DOB");
             String Address = rs.getString("Address");
             String Contact_no = String.valueOf(rs.getInt("Contact_no"));
             String Email = rs.getString("Email");
             String Education = rs.getString("Education");
             String Department = rs.getString("Department");
             String Designation = rs.getString("Designation");
             String Salary = String.valueOf(rs.getInt("Salary"));
             String EPF_no = String.valueOf(rs.getInt("EPF_no"));
             
             String tbData[] = { Employee_ID1, Name, Gender, NIC, DOB, Address, Contact_no, Email, Education, Department, Designation, Salary, EPF_no };
             
             Remove rem = new Remove();
              
             DefaultTableModel tblModel;
             tblModel = (DefaultTableModel) rem.re_table.getModel();
             tblModel.addRow(tbData);
             
             rem.setVisible(true);
             this.hide();
             
             
         } 
         
       
         else
         {
             JOptionPane.showMessageDialog(this, "Employee ID not found.......");
         }
     }   
          catch(Exception ex)
      {
         JOptionPane.showMessageDialog(this, "Employee ID not found.......");
      } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       HR_manager hrm = new HR_manager();
       hrm.setVisible(true);
       this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void employee_id11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_id11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employee_id11ActionPerformed

           
       
         
     
       
     
     
         
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField employee_id11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private Object getSelectedItem() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
